name: adapty_ui_flutter_example
description: Demonstrates how to use the adapty_ui_flutter plugin.
version: 1.0.0
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  adapty_ui_flutter:
    path: ../
  adapty_flutter:
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  uuid: ^3.0.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false
