name: adapty_ui_flutter
description: A new Flutter plugin project.
version: 1.1.0
homepage: https://adapty.io/
repository: https://github.com/adaptyteam/AdaptyUI-Flutter
issue_tracker: https://github.com/adaptyteam/AdaptyUI-Flutter/issues
documentation: https://docs.adapty.io/docs

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  adapty_flutter: ^2.4.4
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.adapty.adapty_ui_flutter
        pluginClass: AdaptyUiFlutterPlugin
      ios:
        pluginClass: AdaptyUiFlutterPlugin
