name: adapty_ui_flutter
description: Extension to the Adapty SDK that allows you to easily add purchase screens to your application.
version: 2.1.3
homepage: https://adapty.io/
repository: https://github.com/adaptyteam/AdaptyUI-Flutter
issue_tracker: https://github.com/adaptyteam/AdaptyUI-Flutter/issues
documentation: https://docs.adapty.io/docs

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adapty_flutter: ^2.10.2
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.adapty.adapty_ui_flutter
        pluginClass: AdaptyUiFlutterPlugin
      ios:
        pluginClass: AdaptyUiFlutterPlugin
